# Generated by Django 5.1.7 on 2025-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='location',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='end_time',
        ),
        migrations.AddField(
            model_name='cinema',
            name='addr',
            field=models.TextField(default='Urmia'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(default='Urmia', max_length=100),
        ),
        migrations.AddField(
            model_name='showtime',
            name='free_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='salable_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیت'), (3, 'بلیت\u200cها تمام شد'), (4, 'فروش بلیت بسته شد'), (5, 'فیلم پخش شد'), (6, 'سانس لغو شد')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='contact_number',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
