# Generated by Django 5.1.7 on 2025-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_showtime_hall_remove_seat_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_showing',
            field=models.BooleanField(default=True),
        ),
    ]
